import {
  lucideLayoutDashboard,
  lucideX,
  lucideCheck,
  lucideChevronDown,
  lucideChevronUp,
  lucidePlus,
  lucideContrast,
  lucideLaptop2,
  lucideSun,
  lucideMoon,
  lucideDumbbell,
  lucideApple,
  lucideGlassWater,
  lucideLeaf,
  lucideSettings,
  lucideListChecks,
  lucideList,
  lucideFlame,
  lucideChevronLeft,
  lucideChevronRight,
  lucideEdit2,
  lucideTrash2,
  lucideAlertTriangle,
  lucideCircleQuestionMark,
  lucideXCircle,
  lucideCheckCircle2
} from "@ng-icons/lucide";

export const APP_ICONS = {
  lucideLayoutDashboard,
  lucideX,
  lucideCheck,
  lucideChevronDown,
  lucideChevronUp,
  lucidePlus,
  lucideContrast,
  lucideLaptop2,
  lucideSun,
  lucideMoon,
  lucideDumbbell,
  lucideApple,
  lucideGlassWater,
  lucideLeaf,
  lucideSettings,
  lucideListChecks,
  lucideList,
  lucideFlame,
  lucideChevronLeft,
  lucideChevronRight,
  lucideEdit2,
  lucideTrash2,
  lucideAlertTriangle,
  lucideCircleQuestionMark,
  lucideXCircle,
  lucideCheckCircle2
} as const;
